version: '3.8'

services:
  frontend:
    image: yourhub/frontend:latest
    restart: always
    networks:
      - app-network

  backend:
    image: yourhub/backend:latest
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
