version: '3.8'
services:
<<<<<<< HEAD
  backend:
    build: ./backend
    container_name: todo-backend
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: todo-frontend
    expose:
      - 80
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: todo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
=======
  frontend:
    image: yourhub/frontend:latest
    restart: always
    networks:
      - app-network

  backend:
    image: yourhub/backend:latest
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
>>>>>>> 2f7c969ba3f2fe114be93cde95b3cdd2d97f9175
